import os
from typing import Dict, Any, Optional

import pandas as pd
from dotenv import load_dotenv
import google.generativeai as genai
from google.api_core.exceptions import NotFound

_ENV_PATH = os.path.join(os.path.dirname(__file__), ".env")
load_dotenv(dotenv_path=_ENV_PATH, override=False)


def _finish_reason_is_max_tokens(response: Any) -> bool:
    """Best-effort check for token-limit truncation across SDK variants."""
    try:
        candidates = getattr(response, "candidates", None) or []
        if not candidates:
            return False
        finish_reason = getattr(candidates[0], "finish_reason", None)
        if finish_reason is None:
            return False
        return "MAX_TOKENS" in str(finish_reason).upper()
    except Exception:
        return False


def _build_prompt(
    summary: Dict[str, Any],
    stats_description: pd.DataFrame,
    correlation: Optional[pd.DataFrame],
    visualization_summaries: str,
    model_results: Optional[Dict[str, Any]],
    problem_type: Optional[str],
) -> str:
    """
    Build a rich, structured prompt describing the dataset,
    EDA, visualizations, correlations and model performance
    for the LLM to generate a full analytics report.
    """
    lines: list[str] = []

    lines.append(
        "You are a senior data scientist. Analyze the dataset, EDA outputs, "
        "visualizations, correlations, and machine learning results below and "
        "produce a detailed analytics report."
    )
    lines.append("")

    lines.append("Dataset Summary:")
    lines.append(str(summary))
    lines.append("")

    lines.append("Statistical Description (head):")
    lines.append(stats_description.head().to_string())
    lines.append("")

    if correlation is not None and not correlation.empty:
        lines.append("Correlation Matrix (head):")
        lines.append(correlation.head().to_string())
    else:
        lines.append("Correlation Matrix:")
        lines.append("Not available (not enough numeric columns).")
    lines.append("")

    lines.append("Visualization Insights (generated by the app):")
    lines.append(visualization_summaries or "No visualization summaries were generated.")
    lines.append("")

    if model_results is not None:
        lines.append("Model Results:")
        lines.append(f"Problem type detected: {problem_type}")
        lines.append(str(model_results))
    else:
        lines.append("Model Results:")
        lines.append(
            "No model was trained (no target column selected or an error occurred)."
        )
    lines.append("")

    lines.append(
        """
Using the information above, generate a **structured report** in plain text.

CRITICAL FORMAT REQUIREMENTS (follow exactly):

- Begin with the single line: `AI Analytics Report` on its own.
- After that, output **only** the following 9 numbered sections, in this exact order.
- Each section heading must be on its own line exactly as shown below
  (same wording and numbering).
- Under each heading, write several clear sentences (and optional bullet points)
  explaining the insights. Avoid one-line summaries.
- Do NOT add any extra titles, introductions, or sections.

The required structure is:

AI Analytics Report

1. Dataset Overview
Explain dataset size, feature types, key variables, and the target variable (if any).

2. Data Quality Insights
Discuss missing values, duplicates, outliers, and overall data completeness or reliability.

3. Exploratory Data Analysis
Explain key distributions, averages, variability, and any notable patterns in the features.

4. Visualization Insights
Interpret what the histograms, boxplots, distribution plots, categorical charts, and correlation
heatmap (if available) reveal about the data.

5. Feature Relationships
Explain meaningful relationships between variables, including strong positive or negative
correlations, and how they might affect the target or business questions.

6. Machine Learning Findings
Describe the problem type, models evaluated, best-performing model, and key performance
metrics in business-friendly language. If no model was trained, explain why and what
would be needed.

7. Key Drivers
Identify which variables appear to be most important drivers of the outcome, using both
correlations and model feature importance when available.

8. Business Insights
Translate technical findings into practical insights that a business stakeholder would
care about. Focus on what the patterns mean for real-world decisions.

9. Recommendations
Provide concrete recommendations (at least 5) on: improving data quality, additional data
to collect, further analyses to run, and how the organization could act on these insights.

Writing style:
- Use clear, non-technical language suitable for business stakeholders while keeping important
  technical details where they help interpretation.
- Use short paragraphs and, where appropriate, bullet points to highlight key findings and actions.
        """.strip()
    )

    return "\n\n".join(lines)


def generate_ai_insights(
    summary: Dict[str, Any],
    stats_description: pd.DataFrame,
    correlation: Optional[pd.DataFrame],
    visualization_summaries: str,
    model_results: Optional[Dict[str, Any]],
    problem_type: Optional[str],
) -> str:
    """
    Call the Gemini API to generate natural language insights
    based on dataset summary, statistics, correlation, and model performance.
    """
    # Streamlit can keep a long-lived process; reload `.env` on each call so
    # editing the file doesn't require a server restart.
    load_dotenv(dotenv_path=_ENV_PATH, override=True)

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY environment variable is not set. "
            "Please set it to your Gemini API key."
        )

    genai.configure(api_key=api_key)

    prompt = _build_prompt(
        summary=summary,
        stats_description=stats_description,
        correlation=correlation,
        visualization_summaries=visualization_summaries,
        model_results=model_results,
        problem_type=problem_type,
    )

    preferred = os.getenv("GEMINI_MODEL")
    # Try a few commonly available model IDs, then fall back to the first
    # available model that supports `generateContent`.
    candidate_model_names = [
        preferred,
        "gemini-1.5-flash-latest",
        "gemini-1.5-flash",
        "models/gemini-1.5-flash",
        "gemini-1.5-pro-latest",
        "gemini-1.5-pro",
        "models/gemini-1.5-pro",
    ]
    candidate_model_names = [m for m in candidate_model_names if m]

    generation_config = genai.types.GenerationConfig(
        temperature=0.3,
        # Higher cap prevents reports from getting cut off mid-section.
        max_output_tokens=4096,
    )

    response = None
    last_err: Exception | None = None
    for model_name in candidate_model_names:
        try:
            model = genai.GenerativeModel(
                model_name=model_name,
                system_instruction="You are an expert data analyst and business consultant.",
            )
            response = model.generate_content(prompt, generation_config=generation_config)
            last_err = None
            break
        except NotFound as e:
            last_err = e

    if response is None:
        # Final fallback: query the API for models and pick the first that supports generateContent.
        try:
            for m in genai.list_models():
                if "generateContent" in getattr(m, "supported_generation_methods", []):
                    model = genai.GenerativeModel(
                        model_name=getattr(m, "name", None) or str(m),
                        system_instruction="You are an expert data analyst and business consultant.",
                    )
                    response = model.generate_content(prompt, generation_config=generation_config)
                    last_err = None
                    break
        except Exception as e:
            last_err = e

    if response is None:
        raise RuntimeError(
            "Unable to call Gemini with any available model. "
            "Optionally set GEMINI_MODEL in your environment."
        ) from last_err

    report_text = (response.text or "").strip()

    # If the model stopped because of output token limit, request continuation
    # and append it so the user sees the complete report.
    if _finish_reason_is_max_tokens(response) and report_text:
        continuation_prompt = (
            "Continue the same report from exactly where it stopped. "
            "Do not restart or repeat earlier sections. "
            "Return only the remaining content."
        )
        for _ in range(2):
            follow_up = model.generate_content(
                f"{continuation_prompt}\n\nReport generated so far:\n{report_text}",
                generation_config=generation_config,
            )
            extra = (follow_up.text or "").strip()
            if extra:
                report_text = f"{report_text}\n\n{extra}".strip()
            if not _finish_reason_is_max_tokens(follow_up):
                break

    return report_text